from .graph import graph_moment_vs_temp
from .graph import graph_moment_vs_field
from .graph import graph_magnetization_vs_temp
from .graph import graph_magnetization_vs_field
from .graph import graph_Bohr_vs_field
from .graph import graph_Bohr_vs_temp
from .graph import graph_susceptibility_vs_temp
from .graph import graph_powder_Xray_intensity_vs_angle
from .graph import ax_transplant